# This workflow is intended to be used for publishing
# docker images when a release is published.
#
# These releases will be tagged with the SHA of the merge commit.
#
# This is intended for stable, semver'd releases.

name: Release to Docker Hub (stable)

on:
  release:
    types:
      - released # trigger when a release is published or a pre-release becomes a release

env:
  namespace: my-org # the organisation name or username to publish to
  repo-name: app-name # the name of the docker image (must be lowercase)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.namespace }}/${{ env.repo-name }}
          tags: |
            ${{ github.ref_name }}
            latest

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: . # the root of the repo
          file: App/Dockerfile # the path to the Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
